version: "2" 
services: 
  django: 
    container_name: django_server 
    image: albertalvarezbruned/django 
    stdin_open: true 
    tty: true 
    volumes: 
      - ./myproject:/myproject/myproject 
    ports: 
      - "8000:8000" 
    depends_on: 
      - db 
  db: 
    image: postgres 

